[features]
seeds = false
skip-lint = false
[programs.localnet]
my_program = "FKkBRJhhYv4qxtr8QnpkwQhPN29TuArzWJptJeRVXepP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/emerson/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
